In [14]:
#To learn about array attributes, let us consider two arrays A and B of different dimensions.
#Each array has attributes ndim (the number of dimensions), shape (the size of each dimension), and size (the total size of the array).

import numpy as np
A=np.array([1,2,3,4,5,6]) #This is a one dimensional array
B=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])     #This is a two dimensional array
print("array A ndim: ", A.ndim)
print("array A shape:", A.shape)
print("array A size: ", A.size)
print("array B ndim: ", B.ndim)
print("array B shape:", B.shape)
print("array B size: ", B.size)

array A ndim:  1
array A shape: (6,)
array A size:  6
array B ndim:  2
array B shape: (3, 3)
array B size:  9


In [15]:
#We also have the 'dtype','itemsize' and 'nbytes' attributes
print("dtype:", B.dtype)
print("itemsize:", B.itemsize, "bytes")
print("nbytes:", B.nbytes, "bytes")

dtype: int32
itemsize: 4 bytes
nbytes: 36 bytes


In [16]:
#Indexing in arrays
#In a one-dimensional array, the ith value can be accessed by specifying the desired index in square brackets, just like lists in Python

A[2]

3

In [17]:
#To index from the end of the array, negative indices can be used.
A[-1]

6

In [18]:
#In a multi-dimensional array, items are accessed with comma-separated tuple of indices
B[2,1]

8

In [19]:
B[1,-1]

6

In [22]:
A[1::2]  # every other element, starting at index 1

array([2, 4, 6])

In [37]:
#Array Slicing

#We use the slice notation, marked by the colon (:) character. This syntax is the same as that of the Python list.
#array[start:stop:step] If these paramaters are unspecified, default will be start=0, stop=size of dimension, step=1.

A[:5]  # first five elements

array([1, 2, 3, 4, 5])

In [23]:
#Multidimensional
B[:2, :2]  # two rows, two columns

array([[1, 2],
       [4, 5]])

In [27]:
B[::-1, ::-1]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [32]:
#Reshaping of arrays is done using 'reshape' method.

grid = np.arange(1, 13).reshape((4, 3))
print(grid)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [53]:
#Also reshaping using the column vector via newaxis, also can be done with row vector.

A[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [38]:
#Array concatenation/joining using 'concatenate' method.

x = np.array([1, 2, 4])
y = np.array([5, 6, 8])
np.concatenate([x, y])

array([1, 2, 4, 5, 6, 8])

In [41]:
np.concatenate([A,x])

array([1, 2, 3, 4, 5, 6, 1, 2, 4])

In [42]:
#For multidimensional arrays
np.concatenate([B,B])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
#Concatenation can also be done horizontally or vertically using np.vstack and np.hstack.

x = np.array([7, 8, 9])
y=np.array([[0],
            [0],
            [0]])
print("Vertically,\n",np.vstack([x, B]))
print("Horizontally,\n",np.hstack([B,y]))

Vertically,
 [[7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]
Horizontally,
 [[1 2 3 0]
 [4 5 6 0]
 [7 8 9 0]]


In [66]:
#Array splitting using 'np.split', 'np.hsplit', and 'np.vsplit'. 
#We pass a list of indices giving the split points.

arr = [1, 2, 3, 4, 5, 6, 7, 8, 9]
x1, x2, x3 = np.split(arr, [3, 5])
print(x1, x2, x3)

[1 2 3] [4 5] [6 7 8 9]


In [67]:
upper, lower = np.vsplit(B, [2])
print("First part:\n",upper)
print("Second part:",lower)

First part:
 [[1 2 3]
 [4 5 6]]
Second part: [[7 8 9]]


In [68]:
left, right = np.hsplit(B, [2])
print("First part:\n",left)
print("Second part:\n",right)

First part:
 [[1 2]
 [4 5]
 [7 8]]
Second part:
 [[3]
 [6]
 [9]]


In [71]:
#Creating copies of an array. Done using the 'copy()' method.

B_copy = B[:2, :2].copy()
print(B_copy)
B_copy[0,0]=99
print(B_copy)
#Original array will not be modified.
print(B)

[[1 2]
 [4 5]]
[[99  2]
 [ 4  5]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
